In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Lab 8 - Multi-layer Perceptron Forward Pass

## Part I
For this exercise you will implement a simple 2-layer perceptron (forward pass)

For the first part you'll write a function that computes the forward pass of a 2-layer perecptron that predicts the prices of houses, using the usual Boston housing dataset.

In [3]:
boston = pd.read_csv('housing.txt', delim_whitespace=True)


C:\Users\Matheus Pinto\AppData\Local\Temp\ipykernel_24492\2042122181.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  boston = pd.read_csv('housing.txt', delim_whitespace=True)


As usual, consider the MEDV as your target variable. 
* Split the data into training, validation and testing (70,15,15)% (you will need this for the next lab as we will build from this lab)

In [ ]:
X = boston.values[:,:-1]
y = boston.iloc[:,-1:]
X_tv, X_test, y_tv, y_test = train_test_split(X, y,test_size=0.15, random_state=189, shuffle=True)
X_train, X_validation, y_train, y_validation = train_test_split(X_tv, y_tv, test_size=0.15/0.85 , random_state=123, shuffle=True) 

[[2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 ... 1.8700e+01 3.9463e+02 2.9400e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


Now you will write the function that computes the forward pass. 
* I provide here a structure that you can follow for your function, but again, feel free to modify it as you see fit.
* Use the sigmoid function as the activation of the hidden layer.
* Don't forget about the biases!
* *It is up to you to think what should be the activation for the output layer.*

In [5]:
def sigmoid_activation(z):
    return 1 / (1 + np.exp(-z))
    

In [6]:
def two_layer_perceptron(X, activation, dim_input, dim_hidden, dim_output):
    """
    Implements the forward pass of a two-layer fully connected perceptron.
    
    Parameters
    ----------
    X : a 2-dimensional array
        the input data
    activation : function
        the activation function to be used for the hidden layer
    dim_input : int
        the dimensionality of the input layer
    dim_hidden : int
        the dimensionality of the hidden layer
    dim_output : int
        the dimensionality of the output layer
    Returns
    -------
    y_pred : float
        the output of the computation of the forward pass of the network
    """
    # pushing the column of bias on X:
    X = np.array(X, dtype=float)
    X_bias = np.c_[X, np.ones(X.shape[0])]
    
    # Initializing the weights with zeros:
    # We have two layers, so
    W_1 = np.random.rand(dim_input+1, dim_hidden)  * 0.01
    W_2 = np.random.rand(dim_hidden+1, dim_output) * 0.01
    
    A1 = X_bias @ W_1
    Z1 = activation(A1)
    Z1 = np.c_[Z1, np.ones(Z1.shape[0])]
    Y = Z1 @ W_2

    y_pred = Y
    return y_pred

dim_input = X_train.shape[1]
dim_hidden = 3
dim_output = 1
y = two_layer_perceptron(X_test, sigmoid_activation,dim_input, dim_hidden, dim_output)
    

Calculate the RMSE of the forward pass. 

In [7]:
def RMSE_foward_pass(y_pred, y_target):
    if (type(y_target) == pd.core.frame.DataFrame):
        y_target = np.array(y_target)

    dif = y_pred - y_target
    dif_squared = dif * dif
    RMSE = (dif_squared.sum() / dif_squared.size) ** (1 / 2)

    return RMSE

## Part II 

For this exercise you will write a function that calculates the forward pass of a 2-layer perceptron that predicts the exact digit from a hand-written image, using the MNIST dataset. 

In [8]:
from sklearn.datasets import load_digits

In [9]:
digits = load_digits()

In [10]:
X = digits.data
y = digits.target

In [11]:
X.shape

(1797, 64)

Again, you will split the data into training, validation and testing.

In [12]:
X_tv, X_test, y_tv, y_test = train_test_split(X, y,test_size=0.15, random_state=189, shuffle=True)
X_train, X_validation, y_train, y_validation = train_test_split(X_tv, y_tv, test_size=0.15/0.85 , random_state=123, shuffle=True) 


Write a function that calculates the forward pass for this multi-class classification problem.
* You will use the sigmoid activation function for the hidden layer.
* For the output layer you will have to write the softmax activation function (you can check the slides)
* __Note:__ you can easily re-use the function that you coded for Part I if you do a simple modification and also include an input argument for the activation of the output layer.

In [13]:
def softmax_activation(z):
    z = np.exp(z)
    softmax = z / np.sum(z, axis=1, keepdims=True)

    return softmax

In [14]:
def forward_pass_multi_class(X, activation, activation_output, dim_input, dim_hidden, dim_output):
    """
    Implements the forward pass of a two-layer fully connected perceptron.
    
    Parameters
    ----------
    X : a 2-dimensional array
        the input data
    activation : function
        the activation function to be used for the hidden layer
    activation_output : function
        the activation function to be used for the output layer
    dim_input : int
        the dimensionality of the input layer
    dim_hidden : int
        the dimensionality of the hidden layer
    dim_output : int
        the dimensionality of the output layer
    Returns
    -------
    y_pred : nd.array
        the output of the computation of the forward pass of the network
    """
    # pushing the column of bias on X:
    X = np.array(X, dtype=float)
    X_bias = np.c_[X, np.ones(X.shape[0])]
    
    # Initializing the weights with zeros:
    # We have two layers, so
    W_1 = np.random.rand(dim_input+1, dim_hidden)  * 0.01
    W_2 = np.random.rand(dim_hidden+1, dim_output) * 0.01
    
    A1 = X_bias @ W_1
    Z1 = activation(A1)
    Z1 = np.c_[Z1, np.ones(Z1.shape[0])]
    Y = Z1 @ W_2

    y_pred = activation_output(Y)
    
    return y_pred

dim_input = X_train.shape[1]
dim_hidden = 3
dim_output = 10
Y_pred = forward_pass_multi_class(X_test, sigmoid_activation,softmax_activation,dim_input, dim_hidden, dim_output)


Lastly, calculate the error of this forward pass using the cross-entropy loss.

In [15]:
def adjust_y_target(y_target):
    if (type(y_target) == pd.core.frame.DataFrame):
        y_target = np.array(y_target)
    Y_target = np.zeros(shape=(y_target.shape[0], 10))
    for l in range(y_target.shape[0]):
        Y_target[l, y_target[l]] = 1.
    
    return Y_target


def cross_entropy_loss(Y_pred, Y_target):
    E = -np.sum(Y_target * np.log(Y_pred)) / Y_pred.shape[0]
    return E


Y_test = adjust_y_target(y_test)

E = cross_entropy_loss(Y_pred, Y_test)

print(E)

2.3024873974484343
